### ISSUE TITLE
Transform hook - enum SyntaxError: Unexpected reserved word

### ISSUE THREAD

**Issue by ricardosouza-logmein** [JennieJi/protobuf2swagger#21]
There's another way to access the enums?
the code from the doc generates an error 
```
const [enum] = args;
               ^^^^
SyntaxError: Unexpected reserved word
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
```

**Comment by ricardosouza-logmein** [comment]
Fix the doc and propose a way to transform enum as string instead of default number
https://github.com/JennieJi/protobuf2swagger/pull/22
